version: '3.1'

services:

  php_site_api:
    image: tidleindigo/serverlocal:latest
    ports:
      - 80:80
    links:
      - db:db
      - redis:redis
      - memcached:memcached
    volumes:
      - ./build_dev/site:/app/site
      - ./sources/api/interne:/app/site/api

  apache_assets:
    image: httpd
    ports:
      - 9000:80
    volumes:
      - ./build_dev/assets:/usr/local/apache2/htdocs

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api_interne

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis
    ports:
      - 6379:6379

  memcached:
    image: memcached
    ports:
      - 11211:11211