version: '3.1'

services:

  api_interne:
    image: indigo/api-interne
    restart: always
    ports:
      - 81:80
    links:
      - db:db
      - redis:redis
      - postgres:postgres
      - mongo:mongo
      - memcached:memcached
    volumes:
      - ./sources/api/interne:/app

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api_interne

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin



  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  memcached:
    image: memcached
    restart: always
    ports:
      - 11211:11211